name: UI Regression Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # هيفتح سيرفر للكروم وسيرفر للفايرفوكس في نفس الوقت
        browser: [chrome, firefox]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Run Tests
        # بنمرر المتصفح من الـ Matrix للكود بتاعك
        run: mvn test -DsuiteXmlFile=src/test/java/tests/postive/testng.xml -Dbrowser=${{ matrix.browser }}

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report Action
        uses: mgrybyk/allure-report-action@v3
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          subfolder: allure-report