name: Swag Labs Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 # تحديث للأصدار الأحدث

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22' # هنا غيرنا الرقم لـ 22
        distribution: 'oracle' # أوراكل هي الأفضل لدعم إصدار 22 حالياً
        cache: maven

    - name: Run All Tests
      run: mvn test